# Generated by Django 4.2.4 on 2023-08-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=40)),
                ('content_id', models.CharField(max_length=40)),
                ('company_data', models.TextField()),
                ('company_url', models.TextField()),
                ('job_content', models.TextField()),
                ('sal', models.TextField()),
                ('job_data', models.TextField()),
            ],
        ),
    ]
