server:
  port: 8089

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jwt:
    secret: goodbesecretpassword123haejunecandysugarcrushpopnewjeansnarutovssasuke

# 로컬 DB
#  datasource:
#    url: jdbc:mysql://localhost:3306/auth?serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 7279
#  서버 DB
  datasource:
    url: jdbc:mariadb://i9a801.p.ssafy.io:3306/auth
    driver-class-name: org.mariadb.jdbc.Driver
    username: ssafy
    password: jinajjang1128!

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    output:
      ansi:
        enabled: always
    database-platform: org.hibernate.dialect.H2Dialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 102133184952-9ihuv92pb6jb2n6cvouaisemgo16li1r.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
#          naver:
#            client-id: jeklm4xYRgBEgrNaTHxf
#            client-secret: JC7fVavVwt
#            scope:
#              - name
#              - email
#            #- profile_image
#            client-name: Naver
#            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8089/login/oauth2/code/naver #코드를 받는 uri(naver 의 콜백 uri)
#          kakao:
#            client-id: 980e563ce14b4616f654759e47932446
#            client-secret: qsMYULNvWu7W4lkTAneAQ0owpkiQiMjM
#            scope:
#              - profile_nickname
#              - account_email
#            client-name: Kakao
#            authorization-grant-type: authorization_code
#            client-authentication-method: POST #카카오는 필수 파라미터를 POST로 요청해야됌!
#            redirect-uri: http://localhost:8089/login/oauth2/code/kakao #코드를 받는 uri(naver 의 콜백 uri)
#        provider: #네이버, 카카오 등 국내 서비스의 provider는 등록되어 있지 않아 사용자가 등록해야된다.
#          naver:
#            authorization-uri: https://nid.naver.com/oauth2.0/authorize #네이버 로그인 창을 받을수 있다
#            token-uri: https://nid.naver.com/oauth2.0/token #토큰을 받는 uri
#            user-info-uri: https://openapi.naver.com/v1/nid/me #프로필 주소를 받는 uri
#            user-name-attribute: response #회원 벙보를 json 형태로 받는데 response 라는 키값으로 네이버가 리턴해줌
#          kakao:
#            authorization-uri: https://kauth.kakao.com/oauth/authorize
#            token-uri: https://kauth.kakao.com/oauth/token
#            user-info-uri: https://kapi.kakao.com/v2/user/me
#            user-name-attribute: kakao_account
            # 스프링 OAuth2-client 라이브러리의 provider 에는 구글,페이스북,트위터가 속해있어 redirect-uri , authorization-grant-type 를 적어주지 않아도 자동으로 고정적으로 등록되어 있다.(적어줘도 된다.) ex) /login/oauth2/facebook, google 로 고정
            # 하지만 네이버나 카카오톡은 Provider 가 아니기 때문에 적어주어야된다. 원하는대로 uri 를 지정할수 있다, 고정되어 있지 않다.